export const defaultProfile: { [key: string]: string | string[] } = {
  name: "",
  phone: "",
  email: "",
  "project manager": "",
  "project coordinator": "",
  "project names": [],
  "project numbers": [],
  "expense request date": "",
  "dates requested": "",
  "days off": "",
  "travel date": "",
  "hotel name": "",
  "rooming with": "",
  "check in date": "",
  "reservation end date": "",
  airfare: "n/a",
  lodging: "n/a",
  gas: "",
  "rental car": "n/a",
  tolls: "n/a",
  parking: "n/a",
  mileage: "n/a",
  supplies: "n/a",
};

export const projects: { [key: string]: string } = {
  "105S017503": "City of Gulfport",
  "105S017506": "Hancock County",
  "105S017504": "City of Waveland",
};
