export const flags: { [key: string]: string } = {
  "-n": "name",
  "--name": "name",
  "--phone": 'phone',
  "-ph": 'phone',
  "--email": 'email',
  "-e": 'email',
  "--pm": "project manager",
  "--pc": "project coordinator",
  "--project": "project",
  "-p": "project",
  "--erd": "expense request date",
  "--dates": "dates requested",
  "-d": "dates requested",
  "--do": "days off",
  "--travel": "travel date",
  "-t": "travel date",
  "--hotel": "hotel name",
  "-h": "hotel name",
  "--rooming": "rooming with",
  "-r": "rooming with",
  "--checkin": "check in date",
  "-ci": "check in date",
  "--reservation": "reservation end date",
  "--red": "reservation end date",
  "--air": "airfare",
  "-a": "airfare",
  "--lodging": "lodging",
  "-l": "lodging",
  "--gas": "gas",
  "-g": "gas",
  "--rental": "rental car",
  "-rc": "rental car",
  "--tolls": "tolls",
  "--tl": "tolls",
  "--parking": "parking",
  "--pk": "parking",
  "--mileage": "mileage",
  "--m": "mileage",
  "--supplies": "supplies",
  "--s": "supplies",
};
